/*
 * Copyright (C) 2021 Natahan Tatan
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/* 
 * \file   MainWindow.h
 * \author Natahan Tatan
 *
 * \version 1.0
 * \date July 13, 2020, 6:21 PM
 */

#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include "gui/yt-dl-gui.hpp"
#include "VideoDL.hpp"
#include <vector>
#include <string>
#include <sstream>

#include <FL/Fl_Native_File_Chooser.H>

/**
 * \class MainWindow MainWindow.h
 * \brief This is an implementation of the UI class generated by Fluid
 * 
 * This class implements the UI class from Fluid. It initializes widgets's callbacks.
 */
class MainWindow: public MainWindowUI
{
    public:
        static std::vector<std::string>  audioTypes;/*<! List of audio codecs supported by youtube-dl */
        
        /*
         * \brief Constructor
         * 
         * Construct a program window
         */
        MainWindow();
        
        ~MainWindow();
        
        /**
         * \brief Callback for trigger update progress bar *INTERNAL USE ONLY*
         * This callback is call by FLTK when render.
         * @param u
         */
        static void UpdateProgress(void* u);
        
    private:
        VideoDL* _current_vdl;/*<! Current download system instance*/
};

#endif /* MAINWINDOW_H */

